language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sxnny/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sxnny/react-test npm test 

after_success:
  - docker build -t sxnny/multi-client ./client
  - docker build -t sxnny/multi-nginx ./nginx
  - docker build -t sxnny/multi-server ./server
  - docker build -t sxnny/multi-worker ./worker  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sxnny/multi-client
  - docker push sxnny/multi-nginx
  - docker push sxnny/multi-server
  - docker push sxnny/multi-worker